package:
  name: go-vncdriver
  version: 0.4.16

source:
  git_url: https://github.com/openai/go-vncdriver.git
  git_tag: v0.4.16
  patches:
    - skip_numpy.patch

build:
  script_env:
    - PYPI_USER
    - PYPI_PASS
  number: 1

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy

test:
  imports:
    - go_vncdriver

about:
  home: https://github.com/openai/go-vncdriver
  summary: fast VNC viewer
