package:
  name: go-vncdriver
  version: 0.4.16

source:
  git_url: https://github.com/openai/go-vncdriver.git
  git_rev: 4e358dce043623df0a98bf4bb370f080c98e7cd7
  patches:
    - setup.patch
    - build.patch

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - numpy
    - setuptools
    - libjpeg-turbo
    - curl

  run:
    - python
    - numpy
    - libjpeg-turbo

test:
  imports:
    - go_vncdriver

about:
  home: https://github.com/openai/go-vncdriver
  summary: fast VNC viewer
